### Registro do Usuário

POST https://projetoadonis.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "Felipeusuario",
    "email": "teste@gmail.com",
    "password": "teste123"
}

###Autenticação do usuário

POST https://projetoadonis.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "password": "teste123"
}